---
title: "Results with distance"
output: html_document
---

```{r, results = 'hide', message = FALSE}
library(foreign)
library(stargazer)
library(arm)
library(rms)
library(msm)
library(systemfit)
library(xtable)
library(gtools)
library(multiwayvcov)
library(numDeriv)
library(interplot)
library(modmarg)
library(tidyverse)
library(stats)
library(haven)
library(systemfit)
library(nnet)
library(sjmisc)
library(maptools)
library(rgeos)
library(Imap)
library(spatstat)
```

```{r}
load("datawork.RData")
```

Re-estimating the model using distance and classical standard errors

```{r}
#reclassifying municipality and district as factor variables
table$id_mun<-factor(table$id_mun)
table$id_dist<-factor(table$id_dist)
```

Running regressions

```{r}
benchmarkPRI.1 <- lm( EPNa ~ distance*PRIstr*highTURNOUT+
                        distance*PRDstr*highTURNOUT+distance*PANstr*highTURNOUT+ 
                         PRI09a+PRD09a+PAN09a+PART09+
                         lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                         EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                         PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                         PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                         CAR+CELULAR+INTERNET+
                         id_mun, data=table, x=TRUE, y=TRUE)


#The same model but testing for other parties: 

benchmarkPRD.1 <- lm( AMLOa ~ distance*PRIstr*highTURNOUT+
                        distance*PRDstr*highTURNOUT+distance*PANstr*highTURNOUT+     
                         PRI09a+PRD09a+PAN09a+PART09+
                         lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                         EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                         PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                         PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                         CAR+CELULAR+INTERNET+
                         id_mun, data=table, x=TRUE, y=TRUE)


benchmarkPAN.1 <- lm( JVMa ~ distance*PRIstr*highTURNOUT+distance*PRDstr*highTURNOUT+distance*PANstr*highTURNOUT+     
                         PRI09a+PRD09a+PAN09a+PART09+
                         lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                         EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                         PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                         PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                         CAR+CELULAR+INTERNET+
                         id_mun, data=table, x=TRUE, y=TRUE)



benchmarkPART.1 <- lm( PART ~ distance*PRIstr*highTURNOUT+distance*PRDstr*highTURNOUT+distance*PANstr*highTURNOUT+     
                          PRI09a+PRD09a+PAN09a+PART09+
                          lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                          EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                          PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                          PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                          CAR+CELULAR+INTERNET+
                          id_mun, data=table, x=TRUE, y=TRUE)

```

```{r}
benchmarkPRI.1.proximity <- lm( EPNa ~ proximity*PRIstr*highTURNOUT+
                        proximity*PRDstr*highTURNOUT+proximity*PANstr*highTURNOUT+ 
                         PRI09a+PRD09a+PAN09a+PART09+
                         lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                         EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                         PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                         PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                         CAR+CELULAR+INTERNET+
                         id_mun, data=table, x=TRUE, y=TRUE)


benchmarkPRD.1.proximity <- lm( AMLOa ~ proximity*PRIstr*highTURNOUT+
                        proximity*PRDstr*highTURNOUT+proximity*PANstr*highTURNOUT+     
                         PRI09a+PRD09a+PAN09a+PART09+
                         lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                         EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                         PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                         PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                         CAR+CELULAR+INTERNET+
                         id_mun, data=table, x=TRUE, y=TRUE)


benchmarkPAN.1.proximity <- lm( JVMa ~ proximity*PRIstr*highTURNOUT+proximity*PRDstr*highTURNOUT+proximity*PANstr*highTURNOUT+     
                         PRI09a+PRD09a+PAN09a+PART09+
                         lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                         EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                         PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                         PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                         CAR+CELULAR+INTERNET+
                         id_mun, data=table, x=TRUE, y=TRUE)



benchmarkPART.1.proximity <- lm( PART ~ proximity*PRIstr*highTURNOUT+proximity*PRDstr*highTURNOUT+proximity*PANstr*highTURNOUT+     
                          PRI09a+PRD09a+PAN09a+PART09+
                          lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
                          EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
                          PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
                          PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
                          CAR+CELULAR+INTERNET+
                          id_mun, data=table, x=TRUE, y=TRUE)
```


```{r}
knitr::kable(broom::tidy(benchmarkPRI.1))
knitr::kable(broom::tidy(benchmarkPRI.1.proximity))
#summary(benchmarkPRI.1)
#summary(benchmarkPRI.1.proximity)
```

## Making plots: 
```{r}
####Predicted vote shares in PRD Mobilized Strongholds

g <- glm( EPNa ~ distance*PRIstr*highTURNOUT+distance*PRDstr*highTURNOUT+distance*PANstr*highTURNOUT+     
           PRI09a+PRD09a+PAN09a+PART09+
           lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
           EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
           PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
           PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
           CAR+CELULAR+INTERNET+
           id_mun, data=table, family = 'gaussian')

distance <- seq(from = min(table$distance), to = max(table$distance), length.out = 3)
marg<-marg(mod = g, var_interest = c("distance"), type = 'levels', data=table[table$PRDstr==1 & table$highTURNOUT==1,],  cofint=.95)
```

```{r}
#getting confidence intervals for the expected PN turnout in PRD strongholds
mean <- marg[[1]]$Margin
upper <- marg[[1]]$'Lower CI (95%)'
lower <- marg[[1]]$'Upper CI (95%)'

dataPRI<-data.frame(cbind(distance, mean, upper, lower))
#dataPRI$distance<-(1/dataPRI$at.prox)
```

```{r}
#same for AMLO
g <- glm(AMLOa ~ distance*PRIstr*highTURNOUT+distance*PRDstr*highTURNOUT+distance*PANstr*highTURNOUT+     
           PRI09a+PRD09a+PAN09a+PART09+
           lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
           EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
           PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
           PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
           CAR+CELULAR+INTERNET+
           id_mun, data=table, family = 'gaussian')

distance <- seq(from = min(table$distance), to = max(table$distance), length.out = 3)
marg<-marg(mod = g, var_interest = c("distance"), type = 'levels', data=table[table$PRDstr==1 & table$highTURNOUT==1,],cofint=.95)

mean <- marg[[1]]$Margin
upper <- marg[[1]]$'Lower CI (95%)'
lower <- marg[[1]]$'Upper CI (95%)'

dataPRD<-data.frame(cbind(distance, mean, upper, lower))
#dataPRD$distance<-(1/dataPRD$at.prox)
```

```{r}
#same for JVMa
g <- glm(JVMa ~ distance*PRIstr*highTURNOUT+distance*PRDstr*highTURNOUT+distance*PANstr*highTURNOUT+     
           PRI09a+PRD09a+PAN09a+PART09+
           lnpop+P18+P65+area+density+INDIGENOUS+CATHOLIC+NONRELIGIOUS+
           EDUCATION+POSTEDUC+ILLITERACY+PROM_HNV+
           PEAprop+PEAfemale+NOINSURANCE+FEMALEJEFA+
           PERROOM+DIRTFLOOR+SERVICES+NO_SERVICES+
           CAR+CELULAR+INTERNET+
           id_mun, data=table, family = 'gaussian')

distance <- seq(from = min(table$distance), to = max(table$distance), length.out = 3)
marg<-marg(mod = g, var_interest = c("distance"), type = 'levels', data=table[table$PRDstr==1 & table$highTURNOUT==1,], cofint=.95)

mean <- marg[[1]]$Margin
upper <- marg[[1]]$'Lower CI (95%)'
lower <- marg[[1]]$'Upper CI (95%)'

dataPAN<-data.frame(cbind(distance, mean, upper, lower))
#dataPAN$distance<-(1/dataPAN$at.prox)
```

```{r}
datasim<-data.frame(rbind(dataPRI, dataPRD, dataPAN))

datasim$dv<-NA
datasim$dv[1:99]<-"Pena Nieto"
datasim$dv[100:198]<-"López Obrador"
datasim$dv[199:297]<-"Vázquez Mota"
```

```{r}
plot(datasim$distance, datasim$mean)
```

```{r}
ggplot()+
  geom_line(data=datasim, aes(x=distance, y=mean,  linetype=dv))+
  geom_ribbon(data=datasim, aes(x=distance,  ymin=lower, 
                      ymax=upper, fill=dv),  alpha=0.5)+theme_bw()+
  ylab("Predicted vote shares (%)")+
  xlab("Distance to Soriana (km)") +
  scale_fill_manual(values = c("#F0E442","red", "deepskyblue2"), name="")+
  scale_linetype_manual(values=c("solid", "longdash","dotted"), name="" )+
  theme(axis.text=element_text(size=18),
        axis.title=element_text(size=18),
        legend.text = element_text(size = 18))
```